name: Build APK
on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool \
            pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev \
            libtinfo5 cmake libssl-dev

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug
          mkdir -p artifacts
          cp bin/*.apk artifacts/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: artifacts/*.apk
          retention-days: 7
